import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import Footer from '../components/Footer/Footer'
import Navbar from '../components/Navbar/Navbar'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Next Realestate',
  description: 'Generated by create next app',
}
/**
 * The Error being highlighted is a Type error
 * It does not break Clerk Api or any app functionality
 * This has to be with the TypeScript configuration
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
