export const cities = [
    { name: 'Karachi', value: 'karachi' },
    { name: 'Lahore', value: 'lahore' },
    { name: 'Islamabad', value: 'islamabad' },
    { name: 'Faisalabad', value: 'faisalabad' },
    { name: 'Rawalpindi', value: 'rawalpindi' },
    { name: 'Peshawar', value: 'peshawar' },
    { name: 'Quetta', value: 'quetta' },
    { name: 'Multan', value: 'multan' },
    { name: 'Sialkot', value: 'sialkot' },
    { name: 'Gujranwala', value: 'gujranwala' },
    { name: 'Bahawalpur', value: 'bahawalpur' },
    { name: 'Sargodha', value: 'sargodha' },
    { name: 'Sukkur', value: 'sukkur' },
    { name: 'Larkana', value: 'larkana' },
    { name: 'Sheikhupura', value: 'sheikhupura' },
    { name: 'Rahim Yar Khan', value: 'rahim_yar_khan' },
    { name: 'Abbottabad', value: 'abbottabad' },
    { name: 'Jhelum', value: 'jhelum' },
    { name: 'Sahiwal', value: 'sahiwal' },
    { name: 'Mardan', value: 'mardan' },
    { name: 'Kasur', value: 'kasur' },
    { name: 'Okara', value: 'okara' },
    { name: 'Mirpur Khas', value: 'mirpur_khas' },
    { name: 'Dera Ghazi Khan', value: 'dera_ghazi_khan' },
    { name: 'Chiniot', value: 'chiniot' },
    { name: 'Mingora', value: 'mingora' },
    { name: 'Nawabshah', value: 'nawabshah' },
    { name: 'Kamoke', value: 'kamoke' },
    { name: 'Hafizabad', value: 'hafizabad' },
    { name: 'Turbat', value: 'turbat' },
];
